#!/bin/bash
#
# -binaryanomaly

cite 'about-alias'
about-alias 'Custom aliases'

# apt alias (also update flatpak)
function _set_pkg_aliases()
{
	if [ -x "$(command -v nala)" ]; then
		alias apts='nala search'
		alias aptshow='nala show'
		alias aptinst='sudo nala install -V'

		if [ -x "$(command -v flatpak)" ]; then
			alias aptupd='sudo nala update && update flatpak update -y'
			alias aptupg='sudo nala upgrade && sudo nala autoremove && sudo flatpak update -y'
			alias aptupgd='sudo nala update && sudo nala upgrade && sudo nala autoremove && sudo flatpak uninstall --unused -y && sudo flatpak update -y'
		else
			alias aptupd='sudo nala update'
			alias aptupg='sudo nala upgrade && sudo nala autoremove'
			alias aptupgd='sudo nala update && sudo nala upgrade && sudo nala autoremove'
		fi

		alias aptrm='sudo nala remove'
		alias aptpurge='sudo nala remove --purge'

		alias chkup='/usr/lib/update-notifier/nala-check -p --human-readable'
		alias chkboot='cat /var/run/reboot-required'

		alias pkgfiles='nala list-files'
	elif [ -x "$(command -v apt)" ]; then
		alias apts='apt-cache search'
		alias aptshow='apt-cache show'
		alias aptinst='sudo apt install -V'

		if [ -x "$(command -v flatpak)" ]; then
			alias aptupd='sudo apt update && update flatpak update -y'
			alias aptupg='sudo apt dist-upgrade -V && sudo apt autoremove && sudo flatpak update -y'
			alias aptupgd='sudo apt update && sudo apt dist-upgrade -V && sudo apt autoremove && sudo flatpak update -y && flatpak uninstall --unused -y'
		else
			alias aptupd='sudo apt update'
			alias aptupg='sudo apt dist-upgrade -V && sudo apt autoremove'
			alias aptupgd='sudo apt update && sudo apt dist-upgrade -V && sudo apt autoremove'
		fi

		alias aptrm='sudo apt remove'
		alias aptpurge='sudo apt remove --purge'

		alias chkup='/usr/lib/update-notifier/apt-check -p --human-readable'
		alias chkboot='cat /var/run/reboot-required'

		alias pkgfiles='dpkg --listfiles'
	fi
}

# neofetch alias
function _set_neofetch_aliases()
{
	if [ -x "$(command -v neofetch)" ]; then
		alias neofetch='neofetch --config $HOME/.neofetch'
	fi
}

_set_pkg_aliases
_set_neofetch_aliases

# other
