#!/bin/bash
#
# -binaryanomaly

cite 'about-alias'
about-alias 'Custom aliases'

# apt alias (also update flatpak)
function _set_pkg_aliases()
{
	if [ -x "$(command -v apt)" ]; then
		alias apts='apt-cache search'
		alias aptshow='apt-cache show'
		alias aptinst='sudo apt install -V'

		if [ -x "$(command -v flatpak)" ]; then
			alias aptupd='sudo apt update && flatpak update -y'
			alias aptupg='sudo apt dist-upgrade -V && sudo apt autoremove && flatpak update -y'
			alias aptupgd='sudo apt update && sudo apt dist-upgrade -V && sudo apt autoremove && flatpak update -y'
		else
			alias aptupd='sudo apt update'
			alias aptupg='sudo apt dist-upgrade -V && sudo apt autoremove'
			alias aptupgd='sudo apt update && sudo apt dist-upgrade -V && sudo apt autoremove'
		fi

		alias aptrm='sudo apt remove'
		alias aptpurge='sudo apt remove --purge'

		alias chkup='/usr/lib/update-notifier/apt-check -p --human-readable'
		alias chkboot='cat /var/run/reboot-required'

		alias pkgfiles='dpkg --listfiles'
	fi
}

# neofetch alias
function _set_neofetch_aliases()
{
	if [ -x "$(command -v neofetch)" ]; then
		alias neofetch='neofetch --config $HOME/.neofetch'
	fi
}

_set_pkg_aliases
_set_neofetch_aliases

# other
